---
title: "PeanutTutorial"
---

This website contains the downloads and handouts for the tutorial *Bayesian Networks in Educational Assessment*. using the `Peanut` Bayesian network toolkit.

You can access this tutorial in two ways:

-   Online viewing through <https://ralmond.net/PeanutTutorial>.

-   Download the source code from <https://github.com/ralmond/PeanutTutorial.git>.

The latter allows you to reproduce the calculations on your own computer using R Studio. See the [Resources](Resources.qmd) page for more information about the software you need to download.

The complete tutorial has the following parts:

1.  [Introduction to Evidence-Centered Assessment Design and Bayesian Networks](ECD.qmd)

2.  [Example Bayesian Networks](BayesNets.qmd)

3.  Using Peanut to Manipulate Bayes nets

<!-- -->

a.  [Scoring using RNetica](Scoring.qmd)
b.  [DiBello Models for Conditional Probability Tables](DiBelloModels.qmd)
c.  [Building a Net with Peanut](Building.qmd)
d.  [Calibrating Model Parameters to Data](Updating.qmd)

<!-- -->

4.  [Dynamic Bayesian Networks](Dynamic.qmd)

An older version of the resources with powerpoint slides is available at <https://myweb.fsu.edu/ralmond/BNinEA/NCMETutorial>


## Powerpoint Slides


[Session 1:  ECD and Bayes nets](https://myweb.fsu.edu/ralmond/BNinEA/NCMETutorial/2021%20BN%20Session%20I.pptx)

[Session 2:  Applications](https://myweb.fsu.edu/ralmond/BNinEA/NCMETutorial/2021%20BN%20Session%20II.pptx)

[Session 3: MCMC](https://myweb.fsu.edu/ralmond/BNinEA/NCMETutorial/2021%20BN%20Session%20IV_MCMC.pptx)



These are from the ISCA slides which are a general stat (as opposed to psychometric) audience.

[Session 1](BNGeneralSession1.pptx)
[Session 2](BNGeneralSession2.pptx)
[Session 3](BNGeneralSession3.pptx)
[Session 4](BNGeneralSession4.pptx)

